image: node:latest

stages:
  - qa
  - deploy

before_script:
  - yarn
  - apk add --update \
        udev \
        ttf-freefont \
        chromium \
        fontconfig \
        pango-dev \
        libxcursor \
        libxdamage \
        cups-libs \
        dbus-libs \
        libxrandr \
        gconf-dev \
        libxscrnsaver \
        libc6-compat \
        && rm -rf /var/cache/apk/*

qa:
  stage: qa
  script:
      - yarn test

pages:
  stage: deploy
  environment:
    name: production
    url: https://stephanemonnot.com/
  script:
      - yarn build
      - mv public oldpublic
      - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
