image: node:latest

stages:
  - qa
  - deploy

before_script:
  - yarn

qa:
  stage: qa
  script:
      - yarn test

pages:
  stage: deploy
  environment:
    name: production
    url: https://stephanemonnot.com/
  script:
      - yarn build
      - mv public oldpublic
      - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
